version: "3"
services:
    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:8.2.2"
        environment:
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "discovery.type=single-node"
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        restart: unless-stopped

    kibana:
        image: "docker.elastic.co/kibana/kibana:8.2.2"
        ports:
            - "5601:5601"
        restart: unless-stopped

    logstash:
        image: "docker.elastic.co/logstash/logstash:8.2.3"
        ports: 
            - "5044:5044"
volumes:
    elasticsearch_data: