version: "3"
services:
    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:8.2.2"
        environment:
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "discovery.type=single-node"
            - "transport.host=localhost"
            - "bootstrap.system_call_filter=false"
        ports:
            - "9200:9200"
        #volumes:
            #- elasticsearch_data:/usr/share/elasticsearch/data

    kibana:
        image: "docker.elastic.co/kibana/kibana:8.2.2"
        ports:
            - "5601:5601"

volumes:
    elasticsearch_data: